blank_issues_enabled: true
contact_links:
  - name: Vragen en discussies / Questions and discussions
    url: https://github.com/MinBZK/MijnOverheidZakelijk/discussions
    about: Stel hier je vraag / Ask your question here
  - name: Issues & stappenplan (MijnOverheidZakelijk)
    url: https://github.com/MinBZK/MijnOverheidZakelijk/issues
    about: Werk aan de FSC-testomgeving wordt bijgehouden in de hoofdrepository
  - name: Contact MOZa
    url: https://mijnoverheidzakelijk.nl/contact/
    about: Neem rechtstreeks contact op met het MOZa-team / Contact the MOZa team directly
